apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker-1
spec:
  serviceName: trino-worker-1 
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker-1
  template:
    metadata:
      labels:
        app: trino-worker-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: trino
        image: trinodb/trino:358
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: trino-cfg-vol
          mountPath: /etc/trino/jvm.config
          subPath: jvm.config
        - name: trino-cfg-vol
          mountPath: /etc/trino/config.properties
          subPath: config.properties.worker
        - name: trino-cfg-vol
          mountPath: /etc/trino/node.properties
          subPath: node.properties
        - name: trino-cfg-vol
          mountPath: /etc/trino/catalog/mysql.properties
          subPath: mysql.properties
        - name: trino-tmp-data
          mountPath: /tmp
        resources:
          requests:
            memory: "1G"
            cpu: 500m
          limits:
            memory: "1G"
            cpu: 500m
        imagePullPolicy: Always
      volumes:
        - name: trino-cfg-vol
          configMap:
            name: trino-configs-1
  volumeClaimTemplates:
  - metadata:
      name: trino-tmp-data
    spec:
      storageClassName: microk8s-hostpath
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi