apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator-1
spec:
  selector:
    matchLabels:
      app: trino-coordinator-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trino-coordinator-1
    spec:
      containers:
      - name: trino
        image: hpdevelop/trino-query-log:359
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: trino-cfg-vol
          mountPath: /etc/trino/jvm.config
          subPath: jvm.config
        - name: trino-cfg-vol
          mountPath: /etc/trino/config.properties
          subPath: config.properties.coordinator
        - name: trino-cfg-vol
          mountPath: /etc/trino/node.properties
          subPath: node.properties
        - name: trino-cfg-vol
          mountPath: /etc/trino/catalog/mysql.properties
          subPath: mysql.properties
        - name: logdata       #同一個pod內的兩個應用共享目錄logdata, 一個寫一個讀
          mountPath: /var/log/trino
        resources:
          requests:
            memory: "1G"
            cpu: 500m
          limits:
            memory: "1G"
            cpu: 500m
        imagePullPolicy: Always
      - image: elastic/filebeat:7.14.0     #提前下載下來到私有映象庫的映象(官方的可能會被牆)
        name: filebeat
        args: [
          "-c", "/opt/filebeat/filebeat.yml",
          "-e",
        ]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: pod_name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: config               #將configmap的內容放到容器本地目錄
          mountPath: /opt/filebeat/
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: logdata       #同一個pod內的兩個應用共享目錄logdata, 一個寫一個讀
          mountPath: /var/log/trino
      volumes:
        - name: trino-cfg-vol
          configMap:
            name: trino-configs-1
        - name: data
          emptyDir: {}
        - name: logdata         #定義logdata為EmptyDir型別掛載目錄
          emptyDir: {}
        - name: config
          configMap:
            name: test-filebeat-config  #使用前面定義的configmap
            items:
            - key: filebeat.yml
              path: filebeat.yml


