apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vitess
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80 # nginx validate port
        - containerPort: 8080 # trino1
        - containerPort: 9090 # trino2
        - containerPort: 5566 # trino-lb
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/nginx.conf"
          subPath: nginx.conf
          readOnly: false
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: nginx-config
            # items:
            # - key: nginx.conf
            #   path: nginx.conf
