
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: "mariadb:10.5"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: tt123456
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "1G"
            cpu: 500m
          limits:
            memory: "1G"
            cpu: 500m
      # volumes:
      # - name: mariadb-for-hive
      #   persistentVolumeClaim:
      #     claimName: maria-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi